#!/usr/bin/env bash

if [ ! command -v cargo &> /dev/null ]; then
  echo "Please install cargo first. <curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh>"
fi

# <https://github.com/eza-community/eza/blob/main/INSTALL.md>
if [ ! command -v eza &> /dev/null ]; then
  cargo install eza
  export alias ls="eza" >> ~/.bashrc
fi

# <https://github.com/io12/pwninit?tab=readme-ov-file#using-cargo>
# if [ ! command -v pwninit &> /dev/null ]; then
  # cargo install pwninit
# fi

