#!/usr/bin/env bash

# Linux

# if [ -x "nvim" ]; then
	curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
	sudo rm -rf /opt/nvim
	sudo tar -C /opt -xzf nvim-linux64.tar.gz

	echo export PATH="$PATH:/opt/nvim-linux64/bin" >> ~/.bashrc
	echo export EDITOR=nvim >> ~/.bashrc
	source ~/.bashrc
# else
	echo "neovim installed"
# fi

