#カーソル移動が楽になるプラグイン
[[plugins]]
repo = 'skanehira/jumpcursor.vim'
hook_add = '''

nmap [j <Plug>(jumpcursor-jump)

'''
lua_add = '''

vim.api.nvim_set_keymap("n", "[j", "<Plug>(jumpcursor-jump)", {silent = true})

'''
