[[plugins]]
repo = 'nordtheme/vim'
hook_add = '''

colorscheme nord

'''
lua_add = '''

--vim.cmd.colorscheme('nord')

'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''

let g:airline_powerline_fonts = 1

let g:airline_theme = 'nord'

let g:airline#extensions#tabline#enabled = 1

'''
lua_add = '''

vim.g.airline_powerline_fonts = 1

vim.g.airline_theme = 'nord'

vim.cmd.colorscheme('default')

vim.g['airline#extensions#tabline#enabled'] = 1

'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#アイコン
[[plugins]]
repo = 'ryanoasis/vim-devicons'
