#
#
#
[[plugins]]
repo = 'natebosch/vim-lsc'
hook_add = '''

let g:lsc_auto_map = v:true

'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'tpope/vim-commentary'
#
#
#

#
#C++
#
[[plugins]]
repo = 'xavierd/clang_complete'
hook_add = '''

let g:clang_library_path='/usr/lib/llvm-14/lib/libclang-14.so.1'

'''

#[[plugins]]
#repo = 'rhysd/vim-clang-format'
#hook_add = '''
#
#au FileType c ClangFormatAutoEnable
#
#let g:clang_format#style_options = {
#	\"BasedOnStyle" : "WebKit"}
#
#	'''
#
#
#
